FROM node:16-alpine

WORKDIR '/home/mopetrov/frontend'


COPY package.json .

RUN mkdir -p node_modules/.cache
RUN chmod -R 777 node_modules/.cache

RUN npm install

COPY . .

CMD ["npm", "run", "start"]